title: Dvir Lafer - Applied Data Scientist
tagline: Dvir Lafer's site | Applied Data Scientist Blog
description: > # this means to ignore newlines until "baseurl:"
    Dvir Lafer - Applied Data Scientist freelancer. From POC and
    acdemic researched to deployed AI models, I will help you
    unleash the insights from your data using variuos AI models.
permalink: ':title/'
baseurl: "/applied-data-scientist-blog" # the subpath of your site, e.g. /blog
url: https://dvirla.github.io # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dvir Lafer # add your name
author-img: dvir-lafer-cropped.png # add your photo
about-author: I am an applied data scientist. Leveraging my skills to tackle diverse challenges across various domains and contributing to cutting-edge researches. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: dvirla # add your Github handle
social-linkedin: dvir-lafer # add your Linkedin handle
social-email: dvirla84@gmail.com# add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
